Cargo.lock
faucet/src/http.rs
runtime/src/lib.rs
runtime/src/pallets/btc_relay.rs
runtime/src/rpc.rs
runtime/src/tests.rs
staked-relayer/Cargo.toml
staked-relayer/src/lib.rs
staked-relayer/src/main.rs
staked-relayer/src/oracle.rs
staked-relayer/src/relay/mod.rs
staked-relayer/src/status.rs
staked-relayer/src/utils.rs
staked-relayer/src/vault.rs
vault/tests/integration_tests.rs

feat: relayers must now be authorized

---

Cargo.lock
runtime/Cargo.toml
runtime/src/lib.rs
runtime/src/pallets/mod.rs

feat: add polkadot types to core

---

runtime/src/rpc.rs

refactor: renable concurrent signing on rpc

---

Cargo.lock
testdata-gen/Cargo.toml
testdata-gen/scripts/run_relayers.sh
testdata-gen/scripts/run_vaults.sh
testdata-gen/src/main.rs

feat: scripts to register multiple vaults & staked relayers

---

bitcoin/src/iter.rs
bitcoin/src/lib.rs
runtime/src/integration/bitcoin_simulator.rs
staked-relayer/README.md
staked-relayer/docker-compose.yml
staked-relayer/src/main.rs
staked-relayer/src/status.rs
staked-relayer/src/vault.rs
vault/README.md
vault/docker-compose.yml
vault/src/lib.rs
vault/src/main.rs
vault/src/replace.rs

feat: staked-relayer and vault clients now wait for Bitcoin to sync

---

runtime/src/lib.rs
runtime/src/pallets/mod.rs

fix: add VaultStatus to core types

---

Cargo.lock
README.md
bitcoin/Cargo.toml
bitcoin/src/lib.rs
faucet/Cargo.toml
runtime/Cargo.toml
runtime/src/pallets/btc_relay.rs
runtime/src/pallets/sla.rs
runtime/src/pallets/vault_registry.rs
runtime/src/rpc.rs
staked-relayer/README.md
vault/README.md

fix: update btc_relay and sla event types

---

Cargo.lock
staked-relayer/Cargo.toml
staked-relayer/src/main.rs
vault/Cargo.toml
vault/src/main.rs

fix: establish parachain connection after bitcoind sync to avoid timeout

---

faucet/src/http.rs

feat: add more logging to faucet client

---

staked-relayer/src/main.rs
vault/src/main.rs

feat: add info log before parachain connect

---

bitcoin/src/lib.rs
faucet/src/main.rs
oracle/src/main.rs
runtime/src/error.rs
runtime/src/rpc.rs
staked-relayer/src/main.rs
testdata-gen/src/main.rs
vault/src/lib.rs
vault/src/main.rs

feat: connect to parachain with retry

---

Cargo.lock
bitcoin/Cargo.toml
bitcoin/src/error.rs
bitcoin/src/iter.rs
bitcoin/src/lib.rs
runtime/src/integration/bitcoin_simulator.rs
staked-relayer/src/main.rs
staked-relayer/src/status.rs
staked-relayer/src/vault.rs
vault/src/main.rs
vault/src/replace.rs

feat: connect to bitcoin with retry

---

staked-relayer/src/error.rs
staked-relayer/src/main.rs

fix(staked-relayer): prettier exit response

---

Cargo.lock
faucet/Cargo.toml
runtime/src/lib.rs
runtime/src/pallets/redeem.rs
runtime/src/pallets/replace.rs
runtime/src/rpc.rs
runtime/src/types.rs
staked-relayer/Cargo.toml
testdata-gen/Cargo.toml
vault/Cargo.toml
vault/src/api.rs
vault/src/error.rs

feat: check for old redeem requests in vault system health check

---

vault/src/error.rs
vault/src/lib.rs
vault/src/main.rs

fix(vault): prettier exit response

---

faucet/src/http.rs
faucet/src/main.rs
staked-relayer/src/http.rs
staked-relayer/src/lib.rs
staked-relayer/src/main.rs
vault/src/faucet.rs
vault/src/http.rs
vault/src/lib.rs

refactor: align http json-rpc impls, calls now async

---

faucet/src/main.rs
oracle/src/main.rs
staked-relayer/src/main.rs
vault/src/main.rs

refactor: env_logger should default to info if unset

---

staked-relayer/src/faucet.rs
staked-relayer/src/lib.rs
staked-relayer/src/main.rs
vault/src/faucet.rs
vault/src/lib.rs

refactor: centralize faucet logic, only fund if not registered

---

Cargo.lock
Cargo.toml
faucet/Cargo.toml
runtime/Cargo.toml
runtime/src/error.rs
runtime/src/integration/mod.rs
runtime/src/rpc.rs
vault/Cargo.toml
vault/tests/integration_tests.rs

Upgrade jsonrpsee to v2 (with subxt), only process finalized events.

Jsonrpsee v2

---

runtime/src/rpc.rs
staked-relayer/src/main.rs

fix: return only active vaults (for liquidation)

---

runtime/src/rpc.rs

fix: increase max_concurrent_requests to 1024

---

vault/src/replace.rs

fix: use correct vault amount in auction replace check

---

Cargo.lock
runtime/src/rpc.rs
staked-relayer/Cargo.toml
staked-relayer/src/core/error.rs
staked-relayer/src/core/mod.rs
staked-relayer/src/core/types.rs
staked-relayer/src/error.rs
staked-relayer/src/lib.rs
staked-relayer/src/main.rs
staked-relayer/src/relay/backing.rs
staked-relayer/src/relay/issuing.rs
staked-relayer/src/relay/mod.rs

refactor: move relayer-core to staked-relayer crate

---

bitcoin/src/iter.rs
bitcoin/src/lib.rs
faucet/src/http.rs
faucet/src/main.rs
runtime/src/integration/bitcoin_simulator.rs
runtime/src/integration/mod.rs
staked-relayer/src/faucet.rs
staked-relayer/src/http.rs
staked-relayer/src/main.rs
staked-relayer/src/oracle.rs
staked-relayer/src/relay/issuing.rs
staked-relayer/src/relay/mod.rs
staked-relayer/src/status.rs
staked-relayer/src/utils.rs
staked-relayer/src/vault.rs
staked-relayer/tests/integration_tests.rs
testdata-gen/src/main.rs
vault/src/cancellation.rs
vault/src/collateral.rs
vault/src/execution.rs
vault/src/faucet.rs
vault/src/http.rs
vault/src/issue.rs
vault/src/lib.rs
vault/src/main.rs
vault/src/redeem.rs
vault/src/refund.rs
vault/src/replace.rs
vault/tests/integration_tests.rs

refactor: simplify usage of arc

---

Cargo.lock
faucet/Cargo.toml
runtime/Cargo.toml
staked-relayer/src/relay/issuing.rs
staked-relayer/src/relay/mod.rs

refactor: match duplicate block relay error and log

---

Cargo.lock
bitcoin/src/iter.rs
bitcoin/src/lib.rs
faucet/Cargo.toml
runtime/Cargo.toml
runtime/src/conn.rs
runtime/src/error.rs
runtime/src/integration/bitcoin_simulator.rs
runtime/src/lib.rs
runtime/src/rpc.rs
runtime/src/types.rs
staked-relayer/src/core/mod.rs
staked-relayer/src/core/types.rs
staked-relayer/src/faucet.rs
staked-relayer/src/http.rs
staked-relayer/src/lib.rs
staked-relayer/src/main.rs
staked-relayer/src/oracle.rs
staked-relayer/src/relay/backing.rs
staked-relayer/src/relay/error.rs
staked-relayer/src/status.rs
staked-relayer/src/system.rs
staked-relayer/src/utils.rs
staked-relayer/src/vault.rs
vault/src/execution.rs
vault/src/replace.rs

feat: handle reconnects in staked-relayer client

---

Cargo.lock
faucet/Cargo.toml
faucet/src/http.rs
faucet/src/main.rs
faucet/src/system.rs

feat: handle reconnects in faucet client

---

bitcoin/src/cli.rs
bitcoin/src/lib.rs
faucet/src/main.rs
oracle/src/main.rs
runtime/src/cli.rs
runtime/src/conn.rs
runtime/src/rpc.rs
staked-relayer/src/core/mod.rs
staked-relayer/src/main.rs
testdata-gen/src/main.rs
vault/src/main.rs

refactor: cli options for manager can be reused

---

bitcoin/src/lib.rs
runtime/src/integration/bitcoin_simulator.rs
runtime/src/rpc.rs
vault/src/cancellation.rs
vault/src/execution.rs
vault/src/replace.rs

They don't do a lot but may as well re-enable...

fix: re-enable execution tests

---

Cargo.lock
bitcoin/Cargo.toml
faucet/Cargo.toml
oracle/Cargo.toml
runtime/Cargo.toml
staked-relayer/Cargo.toml
staked-relayer/tests/integration_tests.rs
testdata-gen/Cargo.toml
vault/Cargo.toml

chore: tidy up dependencies

---

Cargo.lock
runtime/Cargo.toml
runtime/src/conn.rs

https://github.com/interlay/jsonrpsee/commit/1c2ba33e7d9187d687c9ee5ff219108b23fdc1a2

fix: subscription id not dropped if max notifs exceeded

---

runtime/src/lib.rs
staked-relayer/src/relay/mod.rs
vault/src/issue.rs

fix: match issue completed error and log info

---

vault/src/replace.rs

fix: debug log if vault has insufficient funds on auction replace

---

runtime/src/pallets/frame_system.rs

fix: redefine account info

---

vault/src/execution.rs
vault/src/issue.rs
vault/src/lib.rs
vault/src/types.rs

refactor: split vault client types, add tests for reversible hashmap

---

Cargo.lock
faucet/Cargo.toml
faucet/src/http.rs
staked-relayer/src/utils.rs
vault/src/cancellation.rs
vault/src/collateral.rs
vault/src/execution.rs
vault/src/issue.rs
vault/src/system.rs

refactor: join futures where appropriate to improve performance

---

faucet/src/error.rs
faucet/src/system.rs
runtime/src/conn.rs
runtime/src/error.rs
runtime/src/rpc.rs
staked-relayer/src/error.rs
staked-relayer/src/faucet.rs
staked-relayer/src/system.rs
vault/src/error.rs
vault/src/system.rs

fix: throw error on service start if not shutdown

---

Cargo.lock
oracle/src/error.rs
runtime/Cargo.toml
runtime/src/error.rs
runtime/src/lib.rs
runtime/src/rpc.rs
staked-relayer/src/error.rs
staked-relayer/src/relay/mod.rs
vault/src/error.rs
vault/src/issue.rs

refactor: impl module error match guards on runtime error

---

runtime/src/conn.rs

fix: increase max_concurrent_requests and max_notifs_per_subscription

---

faucet/src/http.rs
faucet/src/main.rs
faucet/src/system.rs
runtime/src/conn.rs
runtime/src/lib.rs
staked-relayer/src/main.rs
staked-relayer/src/oracle.rs
staked-relayer/src/relay/mod.rs
staked-relayer/src/system.rs
staked-relayer/src/utils.rs
staked-relayer/src/vault.rs
vault/src/cancellation.rs
vault/src/execution.rs
vault/src/issue.rs
vault/src/lib.rs
vault/src/main.rs
vault/src/system.rs

refactor: propogate service errors

---

.deploy/rust-builder-pod.yaml
Cargo.lock
Jenkinsfile
bitcoin/Cargo.toml
bitcoin/scripts/integration_test.sh
bitcoin/src/iter.rs
bitcoin/src/lib.rs
bitcoin/tests/integration_test.rs
runtime/src/integration/bitcoin_simulator.rs
staked-relayer/src/status.rs
staked-relayer/src/vault.rs
vault/src/execution.rs
vault/src/replace.rs

feat: basic bitcoin integration tests

---

Cargo.lock
bitcoin/src/cli.rs
bitcoin/src/error.rs
bitcoin/src/iter.rs
bitcoin/src/lib.rs
bitcoin/tests/integration_test.rs
faucet/src/system.rs
runtime/src/conn.rs
runtime/src/integration/bitcoin_simulator.rs
runtime/src/rpc.rs
staked-relayer/Cargo.toml
staked-relayer/src/error.rs
staked-relayer/src/main.rs
staked-relayer/src/relay/backing.rs
staked-relayer/src/relay/mod.rs
staked-relayer/src/status.rs
staked-relayer/src/system.rs
staked-relayer/src/vault.rs
staked-relayer/tests/integration_tests.rs
testdata-gen/src/error.rs
testdata-gen/src/main.rs
vault/src/error.rs
vault/src/execution.rs
vault/src/issue.rs
vault/src/main.rs
vault/src/replace.rs
vault/src/system.rs

refactor: better error handling for bitcoin disconnects

---

staked-relayer/src/status.rs

fix: ignore self block submission

---

runtime/src/lib.rs
runtime/src/pallets/mod.rs
runtime/src/pallets/staked_relayers.rs
runtime/src/pallets/utility.rs
runtime/src/rpc.rs

refactor: use utility crate to batch multiple block submissions

---

runtime/src/error.rs
runtime/src/rpc.rs

fix: refresh nonce after signing

---

runtime/src/pallets/exchange_rate_oracle.rs
runtime/src/rpc.rs
testdata-gen/README.md
testdata-gen/src/main.rs

Adds the capability to mark any test keyring as an authorized oracle

feat(testdata-gen): Insert authorized oracle

---

.gitignore
bitcoin/src/addr.rs
bitcoin/src/iter.rs
bitcoin/src/lib.rs
faucet/src/http.rs
runtime/src/cli.rs
runtime/src/conn.rs
runtime/src/error.rs
runtime/src/integration/bitcoin_simulator.rs
runtime/src/integration/mod.rs
runtime/src/pallets/balances_dot.rs
runtime/src/pallets/staked_relayers.rs
runtime/src/rpc.rs
staked-relayer/src/core/mod.rs
staked-relayer/src/faucet.rs
staked-relayer/src/status.rs
staked-relayer/src/system.rs
staked-relayer/src/vault.rs
testdata-gen/src/api.rs
testdata-gen/src/main.rs
vault/src/execution.rs
vault/src/faucet.rs
vault/src/issue.rs
vault/src/replace.rs
vault/src/system.rs
vault/src/types.rs

chore: run cargo clippy and fix all warnings

---

Jenkinsfile

chore: add clippy step to Jenkinsfile

---

Cargo.lock
staked-relayer/Cargo.toml
staked-relayer/src/core/mod.rs
staked-relayer/src/lib.rs
staked-relayer/src/main.rs
staked-relayer/src/relay/issuing.rs
staked-relayer/src/relay/mod.rs
staked-relayer/src/status.rs
staked-relayer/src/system.rs
staked-relayer/src/vault.rs
staked-relayer/tests/integration_tests.rs

feat: add tracing to relayer client

---

Cargo.lock
vault/Cargo.toml
vault/src/cancellation.rs
vault/src/collateral.rs
vault/src/execution.rs
vault/src/issue.rs
vault/src/lib.rs
vault/src/main.rs
vault/src/redeem.rs
vault/src/refund.rs
vault/src/replace.rs
vault/src/retry.rs
vault/src/system.rs
vault/tests/integration_tests.rs

feat: add tracing to vault client

---

Cargo.lock
faucet/Cargo.toml
faucet/src/main.rs
oracle/Cargo.toml
oracle/src/main.rs
staked-relayer/Cargo.toml
staked-relayer/src/main.rs
testdata-gen/Cargo.toml
testdata-gen/src/main.rs
vault/Cargo.toml
vault/src/main.rs

feat: use git-version for clap arg

---

runtime/src/error.rs
service/src/lib.rs

fix: restart clients on any rpc error

---

runtime/src/error.rs
runtime/src/lib.rs
runtime/src/rpc.rs
vault/src/execution.rs
vault/src/retry.rs

refactor: handle errors in redeem retry

---

bitcoin/src/lib.rs
runtime/src/integration/bitcoin_simulator.rs
runtime/src/rpc.rs
service/src/lib.rs
staked-relayer/src/vault.rs
vault/src/cancellation.rs
vault/src/execution.rs
vault/src/issue.rs
vault/src/main.rs
vault/src/redeem.rs
vault/src/refund.rs
vault/src/replace.rs

chore: improve logging of AccountId and H256

---

Cargo.lock
runtime/src/integration/bitcoin_simulator.rs
runtime/src/lib.rs
runtime/src/pallets/mod.rs

chore: upgrade parachain to include new redeem events

---

faucet/src/error.rs
faucet/src/http.rs

refactor: specific faucet funding errors, only update claim on success

---

README.md
faucet/Cargo.toml
faucet/README.md
faucet/src/main.rs
oracle/README.md
oracle/src/main.rs
runtime/src/cli.rs
service/src/lib.rs
staked-relayer/Cargo.toml
staked-relayer/README.md
staked-relayer/src/main.rs
testdata-gen/Cargo.toml
testdata-gen/README.md
testdata-gen/src/main.rs
vault/Cargo.toml
vault/README.md
vault/src/main.rs

refactor: refresh readmes, use --btc-parachain-url for connection

---

Cargo.lock
runtime/src/pallets/security.rs
vault/src/cancellation.rs
vault/src/system.rs

refactor: listen for active block updates for cancellation

---

Cargo.lock

chore: upgrade parachain deps to include liquidation fix

---

service/src/lib.rs
vault/src/faucet.rs
vault/src/system.rs

refactor: print service error on disconnect

---

Cargo.lock
vault/src/issue.rs

fix: don't execute issue below amount + fee

---

bitcoin/src/iter.rs
bitcoin/src/lib.rs
runtime/src/integration/bitcoin_simulator.rs
runtime/src/integration/mod.rs
staked-relayer/src/vault.rs
testdata-gen/src/issue.rs
testdata-gen/src/main.rs
testdata-gen/src/redeem.rs
testdata-gen/src/replace.rs
vault/src/execution.rs
vault/src/lib.rs
vault/src/replace.rs
vault/tests/integration_tests.rs

feat: create/load wallet on error

---

runtime/src/error.rs
runtime/src/lib.rs
vault/src/execution.rs

fix: don't retry execute on invalid chain id

---

Cargo.lock
staked-relayer/src/relay/mod.rs
vault/Cargo.toml

fix: exit relayer on rpc disconnect

---

Cargo.lock
runtime/Cargo.toml
vault/tests/integration_tests.rs

fix: event sub should now subscribe to initialization events

---

Cargo.lock
README.md
rust-toolchain.toml

chore: add rust-toolchain override file

---

vault/src/faucet.rs

fix: only deposit 2/3 of vault allowance from faucet

---

vault/src/collateral.rs
vault/src/system.rs

refactor: use account's free balance if maximum_collateral is None

---

staked-relayer/src/error.rs
vault/src/error.rs
vault/src/issue.rs

refactor: remove unused errors

---

runtime/src/rpc.rs

fix: rpc requests should use finalized blocks

---

Cargo.lock
bitcoin/Cargo.toml
runtime/Cargo.toml
service/Cargo.toml
service/src/telemetry.rs

chore: upgrade parachain and rename telemetry

---

.github/workflows/cargo-docs.yml
.github/workflows/cargo-test.yml

chore: remove ssh-agent from workflow

---

Cargo.lock
bitcoin/Cargo.toml
faucet/Cargo.toml
runtime/Cargo.toml
service/Cargo.toml
vault/Cargo.toml

chore: upgrade to polkadot-v0.9.7

---

README.md

refactor: InterBTC -> interBTC

---

Cargo.lock
bitcoin/Cargo.toml
bitcoin/src/iter.rs
runtime/Cargo.toml
runtime/src/integration/bitcoin_simulator.rs
runtime/src/integration/mod.rs
runtime/src/pallets/vault_registry.rs
runtime/src/rpc.rs
runtime/src/tests.rs
runtime/src/types.rs
vault/src/collateral.rs
vault/src/execution.rs
vault/src/replace.rs

chore: upgrade parachain to 0.8.0

---

.gitlab-ci.yml

feat: publish images to dockerhub

---

Cargo.lock
bitcoin/Cargo.toml
bitcoin/src/error.rs
bitcoin/src/lib.rs
faucet/Cargo.toml
oracle/Cargo.toml
oracle/src/main.rs
runtime/Cargo.toml
runtime/src/conn.rs
runtime/src/error.rs
runtime/src/integration/bitcoin_simulator.rs
runtime/src/retry.rs
runtime/src/rpc.rs
service/Cargo.toml
vault/Cargo.toml
vault/src/execution.rs
vault/src/relay/mod.rs
vault/src/system.rs
vault/tests/relayer_integration_tests.rs
vault/tests/vault_integration_tests.rs

chore: update tokio to v1 and jsonrpc to v18

---

Cargo.lock
oracle/Cargo.toml

chore: upgrade reqwest to run on tokio 1.0

---

Cargo.lock
runtime/Cargo.toml
runtime/src/conn.rs
runtime/src/error.rs
runtime/src/rpc.rs
runtime/src/tests.rs
service/Cargo.toml

chore: update to jsonrpsee 0.3.0

---

vault/src/relay/mod.rs

chore: remove unnecessary closure to satisfy clippy

---

vault/src/vaults.rs

chore: better debug logging on check tx

---

Cargo.lock
bitcoin/Cargo.toml
bitcoin/src/lib.rs
runtime/Cargo.toml
runtime/src/lib.rs

chore: upgrade backoff to 0.3.0

---

vault/src/cancellation.rs
vault/src/system.rs

refactor: cancellation scheduler should subscribe to relay blocks

---

bitcoin/src/error.rs
bitcoin/src/lib.rs

fix: retry bitcoin call on wallet error

---

vault/src/issue.rs

fix: don't exit on rescan error

---

Cargo.lock
bitcoin/Cargo.toml
faucet/Cargo.toml
faucet/src/http.rs
oracle/src/main.rs
runtime/Cargo.toml
runtime/src/integration/mod.rs
runtime/src/lib.rs
runtime/src/pallets/exchange_rate_oracle.rs
runtime/src/pallets/mod.rs
runtime/src/pallets/security.rs
runtime/src/pallets/vault_registry.rs
runtime/src/rpc.rs
runtime/src/tests.rs
runtime/src/types.rs
service/Cargo.toml
vault/Cargo.toml
vault/src/collateral.rs
vault/tests/relayer_integration_tests.rs
vault/tests/vault_integration_tests.rs

chore: upgrade parachain to v0.10.0

---

.github/ISSUE_TEMPLATE/bug_report.md
Cargo.lock
bitcoin/Cargo.toml
faucet/Cargo.toml
oracle/Cargo.toml
runtime/Cargo.toml
service/Cargo.toml
vault/Cargo.toml

chore: bump all crate versions to 0.10.0

---

Cargo.lock
bitcoin/src/lib.rs
oracle/Cargo.toml
oracle/README.md
oracle/src/error.rs
oracle/src/main.rs

feat: submit fee estimates in oracle

---

.github/ISSUE_TEMPLATE/bug_report.md
Cargo.lock
bitcoin/Cargo.toml
faucet/Cargo.toml
oracle/Cargo.toml
runtime/Cargo.toml
runtime/src/integration/mod.rs
runtime/src/lib.rs
runtime/src/pallets/issue.rs
runtime/src/pallets/mod.rs
runtime/src/pallets/redeem.rs
runtime/src/pallets/replace.rs
runtime/src/pallets/vault_registry.rs
runtime/src/rpc.rs
runtime/src/types.rs
service/Cargo.toml
vault/Cargo.toml
vault/src/collateral.rs

chore: upgrade parachain to v0.11.0

---

Cargo.lock
bitcoin/Cargo.toml
oracle/src/error.rs
oracle/src/main.rs
runtime/Cargo.toml
runtime/src/lib.rs

feat: oracle should allow configurable collateral types

---

.github/ISSUE_TEMPLATE/bug_report.md
Cargo.lock
bitcoin/Cargo.toml
faucet/Cargo.toml
oracle/Cargo.toml
runtime/Cargo.toml
service/Cargo.toml
vault/Cargo.toml

chore: bump all crate versions to 1.0.0 to match the parachain

---

.github/workflows/cargo-docs.yml
.github/workflows/cargo-test.yml

Pending https://github.com/actions-rs/toolchain/issues/126

chore: use rust toolchain from config

---

.github/workflows/cargo-test.yml
.gitlab-ci.yml
faucet/Cargo.toml
faucet/src/http.rs
oracle/Cargo.toml

chore: build binaries in parallel using matrix

---

README.md

chore: add metadata instructions to readme

---

.gitlab-ci.yml

fix: bitcoin does not have the feature standalone-metadata

---

.github/workflows/cargo-docs.yml

fix: cargo docs needs features to build

---

faucet/src/http.rs
vault/src/faucet.rs

This will make the faucet send KINT in addition to whatever currency is requested

fix: faucet currency

---

faucet/src/http.rs
faucet/src/main.rs
runtime/src/lib.rs
runtime/src/rpc.rs

feat: configurable native currency id for faucet

---

faucet/src/http.rs

This is a bit of a nasty workaround - making two transfer in the faucet code was so slow that it somehow caused the vault to close the connection to the parachain. We might want to look into _why_ that would make the vault drop the connection, but for now this will do, considering it's only used in testnet

fix: make transfers in faucet concurrent

---

faucet/README.md

chore: update faucet/README.md

---

Cargo.lock
oracle/Cargo.toml
oracle/src/error.rs
oracle/src/main.rs
runtime/src/lib.rs

We need to so we can submit kint in addition to ksm

feat: allow oracle submit multiple exchange rates at once

---

faucet/src/error.rs
faucet/src/http.rs
oracle/src/error.rs
oracle/src/main.rs
runtime/src/types.rs
service/src/lib.rs
vault/src/collateral.rs
vault/src/error.rs
vault/src/execution.rs
vault/src/faucet.rs
vault/src/lib.rs
vault/src/relay/error.rs
vault/src/system.rs

refactor: fix all clippy warnings

---

runtime/src/types.rs
vault/src/system.rs

chore: update confusing vault registration logging

---

runtime/src/conn.rs
runtime/src/error.rs

fix: return error if websocket url is invalid

---

runtime/src/cli.rs
runtime/src/error.rs

fix: require keyring cli args and don't panic

---

faucet/README.md
oracle/README.md
vault/README.md

chore: update all readmes with feature flags

---

vault/src/issue.rs

refactor: change confusing issue execution log message

---

Cargo.lock
faucet/src/main.rs
oracle/src/main.rs
runtime/Cargo.toml
runtime/src/conn.rs
runtime/src/error.rs
runtime/src/integration/mod.rs
runtime/src/lib.rs
runtime/src/rpc.rs
runtime/src/types.rs
vault/src/main.rs

chore: pull in latest subxt changes

---

faucet/src/http.rs
faucet/src/main.rs
runtime/src/lib.rs
runtime/src/rpc.rs
runtime/src/tests.rs
vault/src/system.rs

Fetches the parachain currencies at startup instead of requiring hard-coded constants and error-prone user configuration.

feat: load currencies from constants

---

faucet/README.md
vault/README.md

chore: regenerate cli snippets in readmes

---

bitcoin/src/lib.rs

fix: export BitcoinCoreBuilder for integration tests

---

rust-toolchain.toml

chore: upgrade compiler version

---

runtime/src/error.rs
runtime/src/rpc.rs
vault/src/system.rs

This should prevent the Vault from trying to register with insufficient collateral.

refactor: use min(collateral, free_balance) for registration

---

runtime/src/error.rs
runtime/src/retry.rs
runtime/src/rpc.rs
runtime/src/tests.rs

feat: catch POOL_TOO_LOW_PRIORITY author rpc error

---

service/src/lib.rs

chore: log vault version on first startup

---

bitcoin/src/iter.rs
bitcoin/src/lib.rs
runtime/src/integration/bitcoin_simulator.rs
service/src/lib.rs
vault/src/execution.rs
vault/src/replace.rs
vault/src/system.rs
vault/src/vaults.rs
vault/tests/vault_integration_tests.rs

chore: pretty print btc addresses on register event

---

bitcoin/src/lib.rs
runtime/src/integration/bitcoin_simulator.rs
vault/src/execution.rs

Maybe this won't be needed if we change our approach to fees, but I made the change to help with debugging so making the pr just in case

chore: warn when transaction fee is higher than allowed

---

runtime/src/error.rs

See discussion [here](https://github.com/paritytech/subxt/issues/486#issuecomment-1074023711).

refactor: remove basic error to simplify handling

---

.chglog/config.yml

chore: chglog should match breaking syntax

---

runtime/src/lib.rs
vault/src/cancellation.rs
vault/src/execution.rs

chore: increase MILLISECS_PER_BLOCK to 12000

---

vault/src/system.rs

After 60 seconds of inactivity on the parachain connection, the connection is dropped. I am not sure whether this is done server side or client side. Anyway, the 60 seconds were exceeded in my setup when the bitcoin chain got rescanned upon startup. Fortunately there is an easy workaround: if any subscription is open, the connection is considered to be in use so it does not close after not being actively used. As such, the solution is to move the error event listener to beginning of the code.

fix: prevent parachain inactivity timeout

---

service/src/lib.rs

Otherwise the process will error [here](https://github.com/interlay/interbtc-clients/blob/510c6acbc8aa80076cbb9fe34bf7b5d959363336/vault/src/system.rs#L685).

fix: create master wallet after sync

---

vault/src/faucet.rs
vault/src/system.rs

fix: only register public key after funding

---

bitcoin/src/lib.rs
runtime/src/integration/bitcoin_simulator.rs
runtime/src/integration/mod.rs
runtime/src/rpc.rs
runtime/src/types.rs
service/src/lib.rs
vault/src/execution.rs
vault/src/issue.rs
vault/src/main.rs
vault/src/metrics.rs
vault/src/relay/issuing.rs
vault/src/system.rs
vault/src/vaults.rs

.. I was getting annoyed by all the warnings shown on all prs

chore: fix clippy warnings

---

runtime/src/error.rs
runtime/src/rpc.rs

feat: add spec_version range for backwards compatible upgrades

---

runtime/src/rpc.rs

chore: add shim for kintsugi-testnet spec name

---

runtime/src/rpc.rs
runtime/src/tests.rs

refactor: remove unused relay calls

---

Cargo.lock
runner/Cargo.toml
runner/src/main.rs
runner/src/runner.rs

chore: few runner cleanup nits

---

oracle/src/main.rs

chore: log on oracle success

---

oracle/src/main.rs
runtime/src/rpc.rs

fix: always use coingecko_id and fetch decimals for foreign assets

---

vault/src/system.rs

fix: propagate errors from auto register

---

bitcoin/src/iter.rs
bitcoin/src/lib.rs
runtime/src/integration/bitcoin_simulator.rs
vault/src/execution.rs
vault/src/metrics.rs
vault/src/replace.rs

refactor: remove unused find_duplicate_payments method

---

bitcoin/src/iter.rs
bitcoin/src/lib.rs
runtime/src/integration/bitcoin_simulator.rs
vault/src/execution.rs
vault/src/metrics.rs
vault/src/replace.rs

refactor: remove unused bitcoin rpcs

---

Cargo.lock
bitcoin/Cargo.toml
bitcoin/src/electrs.rs
bitcoin/src/error.rs
bitcoin/src/lib.rs

General code organization in preparation for merging #349

refactor: implement electrs client struct

---

runtime/src/rpc.rs

chore: testnet-kintsugi should use default spec name

---

Cargo.lock
bitcoin/Cargo.toml
faucet/Cargo.toml
oracle/Cargo.toml
runner/Cargo.toml
runtime/Cargo.toml
service/Cargo.toml
vault/Cargo.toml
vault/src/main.rs

chore: upgrade to clap v4

---

bitcoin/src/cli.rs
bitcoin/src/lib.rs
oracle/src/feeds.rs
oracle/src/feeds/dia.rs
runner/src/runner.rs
vault/src/main.rs
vault/src/metrics.rs

chore: update v4 clippy conflict args and resolve clippy warnings

---

bitcoin/src/lib.rs

chore: update comment on initial block sync

---

bitcoin/src/lib.rs
faucet/src/http.rs
oracle/src/feeds.rs
oracle/src/feeds/blockcypher.rs
oracle/src/feeds/coingecko.rs
oracle/src/feeds/kraken.rs
runner/src/main.rs
runner/src/runner.rs
runtime/client/src/lib.rs
runtime/src/cli.rs
runtime/src/error.rs
runtime/src/rpc.rs
vault/src/execution.rs
vault/src/lib.rs
vault/src/main.rs
vault/src/metrics.rs
vault/src/process.rs
vault/src/system.rs

chore: fix clippy warnings after compiler update

---

vault/src/relay/error.rs
vault/src/relay/mod.rs

fix: don't unwrap when collecting headers for relay

---

vault/src/execution.rs

Typo in execution.rs

---

bitcoin/src/light/mod.rs

chore: implement dump_private_key for light client

---

oracle/src/feeds/dia_fair_price.rs

Check if all necessary variables exist (i.e. LockedToken, IssuedToken, Ratio, BaseAssetPrice)

refactor: add additional checks for dia fair price feed
