.gitlab-ci.yml

Trigger gitlab CI builds for pull requests from external repositories.
Ref.: https://gitlab.com/gitlab-org/gitlab/-/issues/5667

Chore: gitlab-ci.yml for external pull requetss

---

.gitlab-ci.yml

Replace CI_COMMIT_REF_SLUG  with CI_COMMIT_REF_NAME 
From gitlab docs:
Variable | GitLab | Runner | Description
-- | -- | -- | --
CI_COMMIT_REF_NAME | 9.0 | all | The branch or tag name for which project is built.
CI_COMMIT_REF_SLUG | 9.0 | all | CI_COMMIT_REF_NAME&nbsp;in lowercase, shortened to 63 bytes, and with everything except&nbsp;0-9&nbsp;and&nbsp;a-z&nbsp;replaced with&nbsp;-. No leading / trailing&nbsp;-. Use in URLs, host names and domain names.

Chore: Use CI_COMMIT_REF_NAME for tagging docker images

---

.github/workflows/cargo-test.yml

The regalloc messages printed (I assume when the parachain's wasm code is loaded) flooded the CI, making it harder to see the actual error messages

chore: don't log regalloc messages in ci

---

vault/src/execution.rs

This should fix the bug where a vault can get reported for theft for doing a refund. Not sure if we should merge already, or if we want to wait until we (1) remove `amount_btc` from the `refund` struct altogether, and (2) we have [these](https://www.notion.so/interlay/Add-integration-test-for-refund-theft-detection-interaction-7905826c7a954c11aedf82f7fc3e1f3d) integration tests

fix: transfer the expected refund amount

---

bitcoin/src/cli.rs
bitcoin/src/lib.rs
bitcoin/tests/integration_test.rs
service/src/lib.rs

Adds a builder for the `BitcoinCore` wrapper to optionally load the Bitcoin network from the `getblockchaininfo` RPC.

feat: load bitcoin network from rpc

---

Cargo.lock
bitcoin/Cargo.toml
bitcoin/src/addr.rs
bitcoin/src/error.rs
bitcoin/src/lib.rs
runtime/src/integration/bitcoin_simulator.rs
service/src/lib.rs
vault/src/relay/mod.rs

We were using an old version of bitcoincore-rpc, which failed when it encountered taproot transactions. While we don't want to fully support taproot transactions just yet, they _can_ be encountered while iterating over transactions upon startup, and it is important not to abort when encountering a taproot transaction (rather, we should ignore them for now).
We used to use greg's fork of rust-bitcoincore-rpc, which uses a fork of rust-bitcoin, which uses a fork of rust-bitcoinconsensus, which changes the cc version. I believe that that are all the changes that were in those forks, but it would be good if someone could check.
The new version of bitcoincore-rpc no longer exposes `hyper` errors. Instead, they now contain a `Box<dyn Error>` type, so we can no longer distinguish a failure to …

fix: upgrade bitcoin rpc so we don't fail on parsing taproot transactions

---

runtime/src/error.rs

Back in https://github.com/interlay/interbtc-clients/pull/230 I changed the error checking. However, I did not check the outdated nonce error. It turns out that not only did it change from `SubxtRuntimeError` to `SubxtBasicError`, the inner error also changed from `RequestError::Call` to `RequestError::Request` due to a change in jsonrpsee. Annoyingly, this error only contains an error message string and not any error code, so we have to search for the error string.. 
Anyway, the incorrect outdated nonce detection caused request_replace to fail, since a transaction would be made from the ui, thus causing the nonce to be outdated. The vault client gave up after one try, which we do on purpose (on disconnect the client would restart), but I still think we should have a careful look at error …

fix: outdated nonce check

---

runtime/src/error.rs
runtime/src/rpc.rs

For whatever reason `impl std::fmt::Display for DispatchError` does not work so this seems to be the only way to capture and interpret the runtime error.

feat: add impl to pretty print runtime error

---

vault/src/system.rs

Subroutine is already guarded by `maybe_run_task`.

chore: remove incorrect todo comment on theft reporting startup

---

service/src/lib.rs
vault/src/execution.rs
vault/src/redeem.rs
vault/src/refund.rs
vault/src/replace.rs
vault/src/system.rs

When we restarted the service (because of disconnect for example), we made sure to cancel the running services. However, we didn't cancel the tasks that were spawned for e.g. executing a redeem. So we start, see an open redeem, and spawn another task to pay and execute the redeem. But if you were unlucky with timing (i.e. first task didn't yet submit the payment to bitcoin core), both tasks could do the payment. 
This pr makes all spawned tasks listen for the shutdown signal.

fix: cancel all spawned tasks

---

runtime/src/error.rs
runtime/src/rpc.rs

This should fix the `Subxt runtime error: Transaction error: The block containing the transaction can no longer be found (perhaps it was on a non-finalized fork?` error

fix: retry when transaction does not get included due to fork

---

faucet/src/main.rs
oracle/src/main.rs
runtime/src/cli.rs
runtime/src/integration/mod.rs
runtime/src/rpc.rs
service/src/lib.rs

This adds a 5 minute timeout on all transaction submissions. Since I am not sure of subxt/jsonrpsee deals well with cancelled subscriptions, and because a timeout might indicate an invalid state in those dependencies, I made _all_ timeouts fire the shutdown signal so a fresh connection will get established upon restart. Without this explicit shutdown signal, non-essential calls (such as bitcoin block relay) would not cause a restart.
The reason for the long timeout time is so that it's less likely the stuck transaction will get included into the parachain after we timeout.

fix: add timeout on transaction submission

---

vault/src/execution.rs
vault/src/system.rs

Without this, a shutdown signal will not restart the service

fix: make the prometheus tasks cancellable

---

bitcoin/src/lib.rs
vault/src/execution.rs

`get_raw_transaction_info` failed when called on a tx that contained a taproot output. This happened when we scanned the mempool for unexecuted redeems upon startup. The underlying cause is that the bitcoin crate does not support taproot yet - this is supposed to come in version 0.28 (wip at time of writing):
https://github.com/rust-bitcoin/rust-bitcoin/milestone/10 
https://github.com/orgs/rust-bitcoin/projects/3 
The fix is to not use `get_raw_transaction_info`, but rather `get_raw_transaction`, which I confirmed _does_ work, and is anyway all we need.
The second change is to not abort processing redeem/replace/refunds when we _do_ fail to parse a specific transaction. 
For future reference, the failing info can be obtained with `bitcoin-cli getrawtransaction …

Fix: dont fail when processing tx containing taproot outputs

---

vault/src/cancellation.rs

This fixes the bug where, after the global issue period just having decreased, the vault tried to cancel old issues prematurely. The fix is to take into account the issue request's period in addition to the global period.

fix: issue cancellation: take into account issuerequest's period

---

bitcoin/src/iter.rs
bitcoin/src/lib.rs
runtime/src/integration/bitcoin_simulator.rs
vault/src/execution.rs
vault/src/issue.rs
vault/src/replace.rs
vault/src/vaults.rs

Apparently there is a 15 second timeout on the bitcoin core requests. For one user, it took about 16 seconds, so the request would timeout, causing the connection to drop and the service to restart. This fix splits scanning into discrete chunks of 100 blocks so we don't run into the timeout. It would be possible to dynamically adjust the chunk size based on the time it takes on a specific machine but I thought it best to keep it as simple as possible. Also note that increasing the timeout wouldn't be a solution, as the expected scan time will only increase for each new mined block.

fix: prevent rescanblockchain timeouts by splitting the scan into chunks

---

vault/src/main.rs

chore: vault should use tracing for exit error

---

runtime/src/lib.rs
runtime/src/rpc.rs
runtime/src/types.rs
service/src/lib.rs
vault/src/execution.rs
vault/src/issue.rs
vault/src/replace.rs
vault/src/system.rs
vault/src/vaults.rs

We could fetch this parameter from the metadata but then it would become very involved to pass the value.

feat: print ss58 encoded addresses by network

---

vault/src/cancellation.rs
vault/src/issue.rs
vault/src/system.rs
vault/tests/vault_integration_tests.rs

Upon restart, the vault would import keys from past issues but it imported the keys from all vault currencies, which led to thefts

fix: don't import key of other vault currencies on startup

---

vault/src/error.rs
vault/src/replace.rs

As discussed on discord, we shouldn't lock additional collateral when accepting a replace request because of the following reasons:
- the vault shouldn't lock additional collateral without the operator's explicit consent
- when we are at the collateral ceiling, all accept_replace calls fail with CurrencyCeilingExceeded
- it fails in the common case where there is no additional collateral available to add in the vault's account
One thing to note is that I removed the `BelowDustAmount` check, which was incorrectly implemented: it was comparing a collateral currency against a wrapped currency, which obviously is incorrect. Furthermore, we already check for dust amount in the parachain so no need to check again in the client.

fix: do not lock additional collateral when accepting replace request

---

vault/src/error.rs
vault/src/faucet.rs
vault/src/system.rs

This PR replaces `--auto-register-with-faucet-url` and `--auto-register-with-collateral` with `--faucet-url=xxx` and `--auto-register=xxx=xxx` which allows the Vault to start with multiple collateral assets.
Example usage:
```
vault --faucet-url 'https://api-testnet.interlay.io/faucet' --auto-register=KSM=faucet --auto-register=KINT=faucet
vault --auto-register=KSM=1000 --auto-register=KINT=1000
```

refactor!: replace auto-register flag for multi-collateral compat

---

runtime/src/error.rs
runtime/src/rpc.rs

Adds declaration of `DEFAULT_SPEC_NAME` constant based on the metadata used for compiling. When connecting to a chain, the clients shut down if the chain `spec_name` does not match `DEFAULT_SPEC_NAME`, printing an error message.

feat: fail to start on metadata mismatch

---

bitcoin/src/lib.rs

In the future we will want to add some support to do automatically increase the fee after a certain period, but for now this at least gives us the option to manually do it

feat: enable RBF on all transactions

---

runtime/src/error.rs
runtime/src/rpc.rs
vault/src/cancellation.rs
vault/src/execution.rs
vault/src/metrics.rs
vault/src/system.rs

Ensures that the `bitcoinNetwork` RPC property specified on the chain matches the chain name returned by `getblockchaininfo` (`mainnet`, `testnet`, `regtest`).

feat: fail to start with wrong bitcoin network

---

bitcoin/src/lib.rs

Two fixes:
- fee-rate: the rpc [supports](https://developer.bitcoin.org/reference/rpc/fundrawtransaction.html) two different units for the fee rate: if you use `feeRate` in camelCase, it is interpreted as `BTC/kvB`. If you use `fee_rate` in snake_case, it is interpreted as `sat/vB`. The one used by our rpc library is the camelCase one, because of [this rename](https://github.com/rust-bitcoin/rust-bitcoincore-rpc/blob/657eebd0dd24c19b7d145b49144f480f5dc09ec3/json/src/lib.rs#L1773)
- We opted in into rbf in `createrawtransaction`. However, we didn't specify inputs as we only add these later in `fundrawtransaction`. Since a transaction is marked for rbf by modifying the sequence number _on the inputs_, setting rbf on `createrawtransaction` effectively was a noop. As a solution, we now opt-in …

fix: fundrawtransaction: opt-in to rbf & correct fee rate

---

oracle/src/error.rs
oracle/src/main.rs

Will be required on interlay. Before, we required either all or none exchange rates to be fixed. Now it is possible to mix both options.
Usage is e.g. `--coingecko=https://api.coingecko.com/api/v3/ --currency-id INTR=6649 --currency-id DOT`

feat: allow oracle to use a combination of fixed and real exchange rates

---

oracle/src/main.rs
runtime/src/error.rs
runtime/src/lib.rs
runtime/src/rpc.rs
runtime/src/tests.rs
runtime/src/types.rs
vault/src/cancellation.rs
vault/src/execution.rs
vault/src/metrics.rs
vault/src/relay/mod.rs
vault/src/system.rs

This allows vaults and oracles to use foreign asset symbols in addition to the hardcoded ones. Since we need to connect to the parachain to be able to determine the parachain id, I had to change the type in the arguments to strings, and only parse them after connecting. Tested on testnet in addition to the integration test

fix: allow foreign assets to be used as cli argument in vault and oracle

---

Cargo.lock
bitcoin/Cargo.toml
bitcoin/src/electrs.rs
bitcoin/src/error.rs
bitcoin/src/iter.rs
bitcoin/src/lib.rs
runtime/src/integration/bitcoin_simulator.rs
vault/src/execution.rs
vault/src/issue.rs
vault/src/metrics.rs
vault/src/relay/mod.rs
vault/src/replace.rs
vault/src/vaults.rs

As per title.
Outstanding question is integration testing. Bitcoin refuses to prune blocks for a very long time - even when issuing a manual `pruneblockchain` rpc call. It doesn't seem realistically possible to create a situation with a pruned transaction during a test run - not without either forking bitcoin-core to see if this behaviour can be patched for more aggressive pruning, or investigating if manually deleting block data may work. A "normal" integration test for the vault would just mock bitcoin-core to return "success" which seems totally useless given that the critical functionality is specifically importing the tx into the bitcoin wallet, hence this PR currently has no tests. I'm open to discussion on this.

feat(pruned-client): implementation of pruned bitcoin node support in the vault, with electrs querying for issue requests

---

runtime/src/rpc.rs

Now that we have the coingecko-id as part of the metadata, make the oracle actually use it

fix: use the coingecko-id from metadata instead of deriving from name

---

.github/workflows/cargo-test.yml
Cargo.lock
Cargo.toml
faucet/src/http.rs
runtime/Cargo.toml
runtime/build.rs
runtime/src/integration/bitcoin_simulator.rs
runtime/src/integration/mod.rs
runtime/src/lib.rs
runtime/src/rpc.rs
runtime/src/tests.rs
vault/src/cancellation.rs
vault/src/execution.rs
vault/src/metrics.rs
vault/src/replace.rs
vault/tests/vault_integration_tests.rs

This reduces the whole testing suite to only about 50 seconds on my machine. The changes in `rpc.rs` are hopefully temporary until [the underlying issue](https://github.com/paritytech/substrate/issues/10279) gets fixed

test: use instant-seal for tests

---

Cargo.lock
runner/Cargo.toml
runner/src/runner.rs

- Retries spawning the vault process with backoff
- Uses the `backoff` crate since it's already a dependency of `interbtc-clients` and can handle both `sync` and `async` closures
- Sets permissions directly when creating the vault file, in an attempt to minimize race conditions

fix(runner): retry on run failure

---

runner/Cargo.toml
runner/src/error.rs
runner/src/main.rs
runner/src/runner.rs

- moves standalone functions into Runner struct
- wrap fallible calls in retries: 
- `ws_client(...)`, due to potential network hiccups
- `delete_downloaded_release(...)`, due to potential locks on the file
- `terminate_proc_and_wait(...)`, if for whatever reason it fails to be `SIGTERM`ed the first time
- `get_request_bytes(...)`, due to potential network hiccups
- adds a few logs

[runner]: Improve error handling

---

runner/README.md
runner/src/error.rs
runner/src/runner.rs

- Restarts child process (vault) if crashed, checked in the main loop of `auto_update`, every `BLOCK_TIME`
- Kills child process before the runner shuts down because of an error. This is implemented both by implementing the `drop` trait for `Runner` and by calling `terminate_proc_and_wait()` if `auto_update()` ever returns

fix: restart child on crash, kill child on runner crash

---

.github/workflows/cargo-test.yml

Uploads `runner` build artifact so it can be released. Since it does not depend on any metadata feature it only runs once, on the `parachain-metadata-kintsugi-testnet` step (since that step is also the only one to run tests).

feat(runner): upload artifact

---

bitcoin/src/iter.rs
bitcoin/src/lib.rs
runtime/src/integration/bitcoin_simulator.rs
vault/src/execution.rs
vault/src/metrics.rs
vault/src/replace.rs
vault/tests/vault_integration_tests.rs

Now that we no longer register the return-to-self address, we don't need to separate the tx creation and sending.

refactor: don't expose LockedTransaction

---

Cargo.lock
service/src/error.rs
vault/Cargo.toml
vault/src/main.rs

Handles termination signals, using a similar approach to https://github.com/interlay/interbtc-clients/pull/330.
This feature makes way for cleaning up the PID file on shutdown, in https://github.com/interlay/interbtc-clients/pull/347
I tried simplifying the scaffolding required for the mocks but still couldn't find a way around using trait methods only as an indirection to the actual implementation.
This feature is opt-in in the code (call `catch_signals()` instead of `start()`) and could be moved to the `service` crate instead.
---
Panics
If the given signal is [forbidden][crate::FORBIDDEN].
If the signal number is negative or larger than internal limit. The limit should be larger than any supported signal the OS supports.
If the relevant Exfiltrator does not support this particular …

feat(vault): handle termination signals

---

Cargo.lock
runner/src/error.rs
runner/src/main.rs
runner/src/runner.rs

- The name of the downloaded executable is no longer determined based on the release URL, but set as a constant (`vault`, instead of e.g. `vault-parachain-metadata-kintsugi-testnet`). This is for compatibility with the interlay docs.
- Handles edge case that led to the runner crashing, in `terminate_proc_and_wait`. If the runner received a termination signal but had no spawned child process, `terminate_proc_and_wait` would propagate an error to the `select!` expression, which performs no further error handling.

fix(runner): crash edge case

---

Cargo.lock
runner/Cargo.toml
runner/src/error.rs
runner/src/main.rs
runner/src/runner.rs

Uses a subxt dynamic query to read the storage map entry for the client release (currently hardcoded to `vault`, but will add a CLI argument to pick the client). Subxt can't nicely decode a custom type so I'm still doing the decoding manually. 
Thanks to subxt, some logic has been removed, along with one unit test.

refactor(runner): Use subxt for reading storage

---

Cargo.lock
bitcoin/Cargo.toml
bitcoin/src/addr.rs
bitcoin/src/iter.rs
bitcoin/src/lib.rs
bitcoin/tests/integration_test.rs
runtime/src/addr.rs
runtime/src/integration/bitcoin_simulator.rs
runtime/src/integration/mod.rs
runtime/src/lib.rs
vault/src/execution.rs
vault/src/issue.rs
vault/src/metrics.rs
vault/src/replace.rs
vault/src/system.rs
vault/tests/vault_integration_tests.rs

Removes generics on `BitcoinCoreApi` trait methods to allow for dynamic dispatch - a prerequisite for merging #349 to support using alternate implementations at runtime. Has the added advantage of being able to remove the `interbtc-bitcoin` dependency from the `bitcoin` crate.

refactor: remove generics on BitcoinCoreApi methods

---

runtime/src/rpc.rs
service/src/lib.rs
vault/src/issue.rs
vault/src/system.rs

Errors which occur in one of the "tasks" are not propagated to the `ConnectionManager` so we should read this reason from the shutdown channel.

refactor: propagate reason for shutdown

---

Cargo.lock
bitcoin/src/lib.rs
vault/src/issue.rs

I was trying the approach where upon timeout, we would abort the rescan and decrease the chunk size. However, it turns out that calling abortrescan shortly followed by a rescanblockchain will almost always fail. Anyway, I found a different solution: to check the rescan status in [getwalletinfo](https://developer.bitcoin.org/reference/rpc/getwalletinfo.html) when we get a timeout. It's not 100% foolproof, since we could have transport errors for other reasons, so the rescan might not have been initiated correctly. But it's the best solution I've found so far

fix: don't abort on rescan timeout

---

vault/src/main.rs

Handles case where the task passed to the signal catcher fails to yield. Now, the task is spawned in its own thread, where it is allowed to block but signals are still caught (on another thread).

feat(vault): Spawn main task in own thread

---

vault/src/main.rs

`block_on` has this documentation: `Run a future to completion on the current thread.`. We want the tasks to use the thread pool, rather than to run on a single thread. Also it's just cleaner

refactor: don't use block_on

---

runner/Cargo.toml
runner/README.md
runner/src/error.rs
runner/src/main.rs
runner/src/runner.rs

Adds `client-type` CLI argument to the runner and updates the readme / comments.
I'm not sure whether using an `enum` that implements `FromStr` and `Display` is the cleanest approach, let me know what you think.

feat(runner): CLI for client type, Readme update

---

bitcoin/src/cli.rs
bitcoin/src/error.rs
bitcoin/src/light/mod.rs
bitcoin/src/light/wallet.rs
service/src/lib.rs

Already included in the `PrivateKey` so there is no need to require it separately.

refactor: remove network flag from cli

---

Cargo.lock
README.md
bitcoin/Cargo.toml
runtime/src/cli.rs
runtime/src/types.rs
service/src/error.rs
vault/Cargo.toml
vault/README.md
vault/src/main.rs

Quick addition to reduce Vault setup overhead / complexity by using the same binary to generate the bitcoin and parachain keys.
Closes #373
Closes #374
Note: this isn't breaking since `RunVault` is the default subcommand - i.e. Vaults will still be able to use the same command as before.
**Examples**
```shell
vault generate-bitcoin-key private-key.wif --network bitcoin
vault generate-parachain-key keyfile.json
```

feat: add subcommands for vault to generate keys

---

Cargo.lock
runner/Cargo.toml
runner/src/runner.rs

Uses checksum of the release to check if re-downloading can be avoided. Validation of the downloaded binary will be done in an upcoming PR.

feat(runner): don't re-download if checksums match

---

Cargo.lock
bitcoin/Cargo.toml
bitcoin/src/addr.rs
bitcoin/src/iter.rs
bitcoin/src/lib.rs
bitcoin/src/light/error.rs
bitcoin/src/light/mod.rs
bitcoin/src/light/wallet.rs
runtime/src/addr.rs
runtime/src/integration/bitcoin_simulator.rs
vault/Cargo.toml
vault/src/execution.rs
vault/src/metrics.rs
vault/src/system.rs
vault/tests/vault_integration_tests.rs

We need the new bitcoincore_rpc library to use `listwalletdir`. This PR updates the dependency, but due to the large amount of changes in the transitive `bitcoin` dependency, no work is done to _use_ `listwalletdir` yet.
Most of the commits contain links to the prs where the change was made in the dependency.

Chore: upgrade bitcoin rpc

---

Cargo.lock
bitcoin/src/lib.rs

This PR should address this error that we've sometimes seen:
```
ERROR vault: Exiting: Other: Failed to load or create bitcoin wallet: BitcoinError: JSON-RPC error: RPC error response: RpcError { code: -4, message: "Wallet file verification failed. Failed to create database path '/home/sander/.bitcoin/wallets/vault-live-polkadot-DOT-IBTC'. Database already exists.", data: None }
```
This error occurred when a wallet gets loaded that hasn't been loaded in a long time - bitcoin will automatically rescan _when loading the wallet_, which can make our rpc call timeout. Since the error thrown is not specific enough to definitely identify timeouts, I added some additional timing logic to identify timeouts more reliably.

fix: more robust wallet loading

---

bitcoin/src/error.rs
service/src/lib.rs

Resolves #382.
- use correct symbol for foreign currencies
- when `symbol` returns an error, propagate an error rather than silently using a default

fix: correct bitcoin walletname for foreign currencies

---

bitcoin/src/lib.rs

Apparently the warning is normally `Some("")`

fix: only print warning if not empty

---

runtime/src/assets.rs
runtime/src/rpc.rs
runtime/src/types.rs
vault/src/system.rs

With the global asset registry cache, Vaults would have to restart to refresh which may not be possible (for example our lib integration tests) so we should listen for select `asset-registry` events and dynamically update this.

feat: update foreign assets dynamically

---

Cargo.lock
faucet/Cargo.toml
oracle/Cargo.toml

Users were getting the error below, which I think might be caused by this: https://github.com/chronotope/chrono/issues/755. The issue indicates that it was fixed in 0.4.21. For this PR I ran `cargo update`, and set any manual dependencies to 0.4.22.
```
"thread 'main' panicked at 'unable to parse localtime info: Io(Os { code: 2, kind: NotFound, message: \"No such file or directory\" })', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.20/src/offset/local/unix.rs:95:37"
```

chore: cargo update

---

bitcoin/src/light/mod.rs
vault/src/system.rs

I think we expected the serialization of `Network::Bitcoin` to be `mainnet` which is not the case so this check was previously superfluous when using mainnet against a testnet parachain.
On a side note, because we removed the checks in service to always restart on any error we will be stuck in a loop now if the wrong Bitcoin network is configured. We should distinguish between recoverable and unrecoverable errors for which this is the latter.

fix: actually detect incorrect bitcoin network

---

runner/src/error.rs
runner/src/runner.rs

As discussed on discord. With this change, people no longer need to run binaries from different folders

fix: runner: use binary name from url

---

runner/src/error.rs
runner/src/runner.rs

`try_load_downloaded_binary` wasn't checking the checksum, so upon startup if the binary was incorrect, it was started anyway. See the `run_binary` right below the `try_load_downloaded_binary`

fix: runner: don't run invalid binaries

---

runner/README.md

- adds build instructions so the runner docs can link to the GitHub readme
- updates the link to the `ClientRelease` struct

feat(runner): improve build docs

---

oracle-config.json
oracle/src/config.rs
oracle/src/currency.rs
oracle/src/error.rs
oracle/src/feeds.rs
oracle/src/feeds/coingecko.rs
oracle/src/feeds/dia.rs
oracle/src/feeds/gateio.rs
oracle/src/feeds/kraken.rs
oracle/src/main.rs

Deserializes into `Currency::Symbol` and `Currency::SymbolAndPath` to support overriding the exchange path.
Closes #399

feat: extend oracle currency type to support symbol=path syntax

---

faucet/src/main.rs
service/src/error.rs
service/src/lib.rs
vault/src/error.rs
vault/src/execution.rs
vault/src/issue.rs
vault/src/main.rs
vault/src/metrics.rs
vault/src/process.rs
vault/src/redeem.rs
vault/src/refund.rs
vault/src/relay/error.rs
vault/src/relay/mod.rs
vault/src/replace.rs
vault/src/system.rs

See the comment on this PR: https://github.com/interlay/interbtc-clients/pull/389
> On a side note, because we removed the checks in service to always restart on any error we will be stuck in a loop now if the wrong Bitcoin network is configured. We should distinguish between recoverable and unrecoverable errors for which this is the latter.
Specifies `Abort` and `Retry` variants on the `service::Error` enum to allow the consumer to propagate a hard-error to the `ConnectionManager`.
On a related note, I'm not sure there is any justification for the `service` logic to have its own crate since it is only ever consumed by the `vault` binary. I wonder if we should fold it in?

refactor: allow service to abort on some errors

---

.deploy/monitoring/prometheus.yml
.deploy/monitoring/rules.yml
.deploy/monitoring/test.yml

Add/improve Prometheus rules for:
* vault startup doom loop (if bitcoind can't service RPC requests in time)
* new redeem not serviced yet
* below secure threshold
In particular, set a minimum (0.01) for some values to avoid false negative alerts.

Prometheus rules for redeem not serviced, and crash loop

---

Cargo.lock
Cargo.toml
faucet/src/http.rs
runtime/Cargo.toml
runtime/client/Cargo.toml
runtime/client/src/lib.rs
runtime/src/cli.rs
runtime/src/error.rs
runtime/src/integration/mod.rs
runtime/src/lib.rs
runtime/src/rpc.rs
runtime/src/types.rs
vault/Cargo.toml
vault/src/execution.rs
vault/src/main.rs
vault/tests/vault_integration_tests.rs

Upgrades `subxt` to `0.23.0` and `jsonrpsee` to `0.15.1`.

refactor: use proper subxt upstream

---

faucet/src/main.rs
oracle/src/main.rs
runtime/src/integration/mod.rs
runtime/src/lib.rs
runtime/src/rpc.rs
runtime/src/shutdown.rs
service/src/lib.rs
vault/src/execution.rs
vault/src/system.rs
vault/tests/vault_integration_tests.rs

When an error is received in transcation stream in `execution::execute_open_requests`, we have to make a choice. Either we restart or continue processing. Both options have their risks: if we restart, it's possible that the vault will never manage to start up, causing us tofail to process requests. On the other hand, if we ignore transactions,we risk double paying. We choose to restart only for network errors, since these are not expected to be persistent. Other errors could be persistent, so we keep going.
I created a `ShutdownSender` struct that checks if a shutdown signal was sent before a receiver started listening. Without this, such events would be missed and the service would not shut down.

Fix: bail on stream failure

---

.github/workflows/cargo-docs.yml

The docs build is [failing](https://github.com/interlay/interbtc-clients/actions/runs/3532233812/jobs/5926340162) with the same `protoc` error as in [this run](https://github.com/interlay/interbtc-clients/actions/runs/3524840585/jobs/5910782021), this patch should fix that

fix: install protobuf before docs build

---

runtime/src/error.rs
runtime/src/lib.rs
runtime/src/types.rs
service/src/lib.rs
vault/src/system.rs

and abort the process if the required threshold is not set. We saw an error on testnet where the Vault would fail to shutdown if started with an invalid currency - i.e. there was no threshold set for that collateral type. The error listener would block shutdown since nothing actually sent the shutdown signal. This was because the error was from the startup sequence, not the spawned sub-tasks where we usually incur errors.

Always send shutdown signal on error

---

faucet/README.md

The faucet config has now been moved into a file, the readme is updated accordingly. The `--help` format has changed, I suppose it's because of the newer `clap` version?

chore(faucet): Update readme

---

Cargo.lock
faucet/Cargo.toml
faucet/src/lib.rs
faucet/src/main.rs
vault/Cargo.toml
vault/src/error.rs
vault/src/faucet.rs

The faucet http api was changed in https://github.com/interlay/interbtc-clients/pull/422 but the vault side was not updated, resulting in vaults attempting to register with ridiculous amounts.

fix: vault registration when using faucet

---

Cargo.lock
oracle/src/feeds/dia.rs

Prices that were fetched from DIA were incorrect, we need to use the reciprocal. Also making the trailing slash of the dia url optional. Currently the path is required to not have a trailing slash, which is inconsistent with the other feeds.

fix(oracle): return asset-per-usd instead of usd-per-asset

---

Cargo.lock
runtime/src/assets.rs
runtime/src/error.rs
runtime/src/lib.rs
runtime/src/rpc.rs
runtime/src/tests.rs
runtime/src/types.rs
vault/README.md
vault/Untitled-1
vault/src/cancellation.rs
vault/src/execution.rs
vault/src/metrics.rs
vault/src/system.rs

Adds the ability to run vaults with a lend token currency (e.g. `QKSM`, `QUSDT`). The client reads current lending markets from storage to determine the (`underlying`, `lend_token`) pairs and then listens for `NewMarketEvent` and `UpdatedMarketEvent` to keep the pairs up-to-date.
After some investigation with @sander2, it turns out that all keys from storage maps that use the `Blake2_128Concat` hasher have a 48 byte prefix than needs to be removed to decode the key. This can replace the way keys are decoded throughout the repo (for instance, in `get_foreign_assets_metadata`), and doing that would also allow for reusing a single key-decoding function.
This PR was tested on `wss://kintnet-api.interlay.io/parachain` with `QKSM`, `QUSDT` and `QKBTC` to ensure the client succesfully registers …

feat(vault): Lend Token collateral

---

Cargo.lock
oracle/Cargo.toml
oracle/src/main.rs

Closes #454
Explicitly catch termination signals as suggested [here](https://stackoverflow.com/a/60812082) - there is an issue with using the oracle client in docker where it fails to shutdown immediately.

feat: add signal-hook to oracle client

---

Cargo.lock
faucet/src/http.rs
runtime/src/assets.rs
runtime/src/lib.rs
vault/src/metrics.rs

- Bug 1: The current approach to building a metrics label out of a currecy (e.g. `vault_id.collateral_currency().inner()`) only has a `symbol()` entry defined for `CurrencyId::Token` types. It would call some function other than [the one](https://github.com/interlay/interbtc-clients/blob/95f96e6aaca33406f710f612d26af439cac426f8/runtime/src/assets.rs#L177) in the `RuntimeCurrencyInfo` trait. This results in metrics for foreign assets having an `_IBTC` label instead of `USDT_IBTC` (see the [discord user report](https://discord.com/channels/745259537707040778/991617172407337030/1091476550542688369)).
- The fix removes the `.inner()` access and calls `.symbol()` directly on the `CurrencyId`. I also added a unit test for qtoken vaults to make sure we won't have the same problem.
- Bug 2: …

fix(metrics): ForeignAsset and LendToken collateral formatting and parsing

---

Cargo.lock
service/src/lib.rs
vault/Cargo.toml
vault/src/error.rs
vault/src/issue.rs
vault/src/main.rs
vault/src/system.rs
vault/tests/vault_integration_tests.rs

To address https://github.com/interlay/interbtc-clients/issues/471 .
Note that I went with another approach - rather than storing data in a hacky way inside the bitcoin wallet, I store it in a rocksdb (since we'll be stateful anyway with https://github.com/interlay/interbtc-clients/pull/246). I wrote it in such a way that the database can be removed without any bad side-effects: it will just rescan everything again. This means that users don't necessarily have to copy over the database when migrating their vaults to other servers

fix: save rescanning progress

---

.gitignore
Cargo.lock
faucet/Cargo.toml
faucet/src/error.rs
faucet/src/http.rs
faucet/src/lib.rs
faucet/src/main.rs
runtime/src/error.rs
runtime/src/rpc.rs
vault/src/metrics.rs
vault/src/replace.rs

Closes https://github.com/interlay/interbtc-clients/issues/478
- Flush data to disk
- Cache claim before transfer, revert on error
- Check T&Cs have been signed if `auth_url` set
Manually tested to avoid spending too much time on this right now before launch setting up mocks, etc.. The tests are anyway *very* slow so I would like to spend time refactoring this code anyway. It would also be nice to do away with the encoded input parameter to simplify manual testing.

refactor: better caching, optional auth check

---

runtime/src/integration/mod.rs
scripts/run_parachain_node.sh

`docker-compose` stopped receiving updates, see https://docs.docker.com/compose/migrate/ .
This migrates the tests to use v2, which is `docker compose` rather than `docker-compose`. The CI still uses v1.
I had to setup my docker to allow non-root users access. To be more safe, I switched to [rootless docker](https://docs.docker.com/engine/security/rootless/) which I installed with [these instructions](https://www.liquidweb.com/kb/how-to-docker-rootless-containers/). I then installed the docker compose plugin based on the steps [here](https://docs.docker.com/engine/security/rootless/).

chore: upgrade to docker compose v2

---

service/src/lib.rs

Otherwise the migration will fail [here](https://github.com/interlay/interbtc-clients/blob/fe03c49fc60de1a1ff05a77358841a3b7ba0d897/vault/src/system.rs#L302)

fix: create shared wallet

---

bitcoin/src/electrs/types.rs
bitcoin/src/lib.rs
vault/src/system.rs

Succeeds https://github.com/interlay/interbtc-clients/pull/516
Fixes an issue with the migration when using a pruned bitcoin core node, because the shared wallet doesn't know which imported funds have been spent we need to manually remove those.

fix: migration for pruned nodes

---

bitcoin/src/electrs/mod.rs
bitcoin/src/electrs/types.rs
bitcoin/src/iter.rs
bitcoin/src/lib.rs
bitcoin/src/light/mod.rs
bitcoin/tests/integration_test.rs
runtime/src/integration/bitcoin_simulator.rs
vault/src/connection_manager.rs
vault/src/execution.rs
vault/src/issue.rs
vault/src/lib.rs
vault/src/metrics.rs
vault/src/replace.rs
vault/src/system.rs
vault/tests/vault_integration_tests.rs

Reverts [this](https://github.com/interlay/interbtc-clients/pull/518) fix which did not work as expected. Here is a recap of the problem with the failed migration which occurred on Kintsugi:
- wallet migration imports all addresses with funds to shared wallet
- pruned nodes use electrs to reimport all issue address funds
- some of these issue addresses are already spent
- new wallet doesn't have context of spent utxos because it is pruned and we can't rescan
The only way to fix this now is by sweeping the funds and then only reimporting funds after the sweeping transaction:
- sweep all funds from currency specific wallet to shared
- remove all pruned funds from shared wallet
- this is to recover the shared wallet from the failed migration
- it assumes new issues are already recorded by …

fix: sweep funds into shared wallet

---

oracle/src/config.rs
oracle/src/error.rs
oracle/src/feeds.rs
oracle/src/feeds/dia_fair_price.rs
oracle/src/main.rs

Corresponding new configs: https://github.com/interlay/interlay-devops/pull/15
Output with new config:
Interlay:
`[2023-11-16T22:03:17Z DEBUG oracle] Collected prices: [CurrencyPairAndPrice { pair: CurrencyPair { base: Symbol("BTC"), quote: Symbol("INTR") }, price: 1464167.4304740096 }, CurrencyPairAndPrice { pair: CurrencyPair { base: Symbol("BTC"), quote: Symbol("DOT") }, price: 6706.458319361545 }, CurrencyPairAndPrice { pair: CurrencyPair { base: Symbol("BTC"), quote: Symbol("USDT") }, price: 36036.036036036036 }, CurrencyPairAndPrice { pair: CurrencyPair { base: Symbol("BTC"), quote: Symbol("VDOT") }, price: 5515.5137103648785 }]`
Kintsugi:
`[2023-11-16T22:04:22Z DEBUG oracle] Collected prices: [CurrencyPairAndPrice { pair: CurrencyPair { base: Symbol("BTC"), quote: Symbol("KINT") }, …

fix: allow oracles composed of different feeds

---

Cargo.lock
Cargo.toml
bitcoin/Cargo.toml
faucet/Cargo.toml
oracle/Cargo.toml
runner/Cargo.toml
runtime/Cargo.toml
runtime/src/cli.rs
runtime/src/lib.rs
runtime/src/rpc.rs
runtime/src/types.rs
vault/Cargo.toml

Removes all patches and instead uses subxt versioning, the parachain dependencies have been feature-gated to not pull in additional Substrate dependencies. In the future we should rely on the metadata where possible and only substitute basic types (or those we control such as `CurrencyId`) - for example I removed the manual `RichDispatchError` decoding. Also made some superfluous cleanups to make the runtime crate look nicer.
Note that `Cargo.lock` actually got bigger because we're pulling in the weak dependency (`sp-runtime`) from `interbtc-primitives` (due to https://github.com/rust-lang/cargo/issues/10801) but AFAIK these packages aren't compiled.

chore: cleanup dependencies
